# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Working Title
email: thejimnicholson+blog@outlook.com
author: Jim Nicholson
description: > # this means to ignore newlines until "baseurl"
  brief notes on things
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thejimnicholson.github.io" # the base hostname & protocol for your site
twitter_username: devopsjames
github_username:  thejimnicholson
facebook_username: jim.nicholson
linkedin_username: jimnicholson
keybase_identity: https://keybase.io/thejimnicholson
twitch_user: flannags
remote_theme: BlackRockDigital/startbootstrap-clean-blog-jekyll
repository: thejimnicholson/thejimnicholson.github.io
github: [metadata]
# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
defaults:
  - 
    scope:
      path: ""
    values:
      background: /assets/site/sky_hole.jpeg 
